### ISSUE TITLE
Some example with middleware.buddy?

### ISSUE THREAD

**Issue by hden** [duct-framework/module.ataraxy#4]
I can't seem to get it to work.

```clojure
{:duct.core/project-ns   foo
 :duct.module/ataraxy    {"/" ^:auth/basic[:index]}
 :foo.handler/index      {}
 :duct.middleware.buddy/authentication
 {:backend :basic
  :realm   "Example"
  :authfn  #ig/ref :example.auth/basic}
 :example.auth/basic {}}
```

Thanks in advance.

**Comment by weavejester** [comment]
Your Buddy authentication middleware is:

    :duct.middleware.buddy/authentication

But the Ataraxy module expects the middleware to be in the following form to be included automatically (see the README):

    :foo.middleware[.<namespace>]/<name>

This means you'll need to put the middleware binding in manually. If you take a look at the advanced section of the README, it shows you an example. In your case, you want something like:

```edn
:duct.module/ataraxy  {"/" ^:auth/basic [:index]}
:duct.handler/ataraxy {:auth/basic #ig/ref :duct.middleware.buddy/authentication}
```

Also note that the Buddy authentication doesn't limit access to pages. For that, the [restrict](https://funcool.github.io/buddy-auth/latest/api/buddy.auth.accessrules.html#var-restrict) function is necessary.

**Comment by hden** [comment]
Cool. Thanks!
