### ISSUE TITLE
Buddy authentication middleware not working

### ISSUE THREAD

**Issue by wwiill** [duct-framework/module.ataraxy#6]
I am not able to get authentication to work with the example below. Basically when I hit`http :3000` it returns 200

Full `config.edn` below:
```
{:duct.core/project-ns duct-service
 :duct.core/environment :production

 :duct.module/logging {}
 :duct.module.web/api {}

 :duct-service.middleware/jws-auth
 {:backend :jws
  :secret "somesecret"}

 :duct.module/ataraxy
 {[:get "/"]
  ^:jws-auth [:entries/list]}

 [:duct.handler.static/ok :duct-service.handler.entries/list]
 {:body {:entries "hello"}}
 }
```

jws-auth middleware is a direct copy of the buddy middleware with some println added:
```
(ns duct-service.middleware
  (:require [buddy.auth.middleware :as buddy]
            [buddy.auth.backends :as backend]
            [integrant.core :as ig]))

(def backends
  {:basic   backend/basic
   :session (fn [_] (backend/session))
   :token   backend/token
   :jws     backend/jws
   :jwe     backend/jwe})

(defn wrap-debugger [handler]
  (fn [request]
    (println "identity:" (:identity request))
    (handler request)))

(defmethod ig/init-key ::jws-auth
  [_ {:keys [backend] :as config}]
  (let [backend-fn (backends backend)
        config     (dissoc config :backend)
        _ (println config backend-fn)]
    (fn [handler]
      (-> handler
          wrap-debugger
          (buddy/wrap-authentication (backend-fn config))))))
```

**Comment by weavejester** [comment]
What happens with `wrap-debugger`? Does it print?

**Comment by wwiill** [comment]
Yes, it prints `:identity nil`

**Comment by weavejester** [comment]
Ah, so I've looked into this and reminded myself exactly what `wrap-authentication` actually does. I've been so deep in other code I'd forgotten. It just sets the `:identify` key on the request map - it doesn't actually restrict access to handlers.

You can solve this by binding the `:identify` key in the Ataraxy route, making it a required key. However, I believe that will result in a 400 error (it might be a good idea to make that 403 by default for `:identity).

You could also wrap the [buddy.auth.accessrules/restrict](https://funcool.github.io/buddy-auth/latest/api/buddy.auth.accessrules.html#var-restrict) function.

**Comment by wwiill** [comment]
Thanks for clarifying
